config/routes.rb
Svatba::Application.routes.draw do

   root 'home#index'
   
    resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new' , via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'  , via: :get
  match '/dary',  to: 'presents#index'   , via: :get
  match '/snoubenci',  to: 'about_us#index'      , via: :get
  match '/snoubenci_galerie',  to: 'galleries#index'   , via: :get
  match '/zenich_galerie',  to: 'groom_galleries#index'  , via: :get
  match '/zenich',  to: 'groom#index'   , via: :get
  match '/nevesta',  to: 'bride#index'   , via: :get
  match '/nevesta_galerie',  to: 'bride#gallery'  , via: :get
  match '/home',    to: 'home#home'      , via: :get
  match '/aktuality',    to: 'home#aktuality'     , via: :get
  match '/dary',    to: 'home#dary'   , via: :get
  match '/program',    to: 'home#program'   , via: :get
  match '/kontakty',    to: 'home#kontakty'  , via: :get

  post "gallery/create"
  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :pictures

  resources :groom_galleries do
    resources :groom_pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :groom_pictures

  resources :bride_galleries do
    resources :bride_pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :bride_pictures

   resources :presents do
     member do
       get 'taken_toggle'
     end
end

  

end

app/models/present.rb
# == Schema Information
#
# Table name: presents
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  pole       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Present < ActiveRecord::Base
 attr_accessible :name, :pole, :user_id, :text
  belongs_to :user



end

app/controllers/presents_controller.rb
# coding: utf-8
class PresentsController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :new]

 # GET /presents
  # GET /presents.json
  def index
    @presents = Present.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @presents }
    end
  end



  # GET /presents/1
  # GET /presents/1.json
  def show
    @present = Present.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @present }
    end
  end

  # GET /presents/new
  # GET /presents/new.json
  def new
    @present = Present.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @present }
    end

  end

  # GET /presents/1/edit
  def edit
    @present = Present.find(params[:id])
  end

  # POST /presents
  # POST /presents.json
  def create
    @present = Present.new(present_params)

    @present.save
    redirect_to @present
  end



  # PUT /presents/1
  # PUT /presents/1.json
  def update
    @present = Present.find(params[:id])

    respond_to do |format|
      if @present.update_attributes(params[:present])
        format.html { redirect_to @present, notice: 'Dar byl úspěšně aktualizován' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presents/1
  # DELETE /presents/1.json
  def destroy
    @present = Present.find(params[:id])
    @present.destroy

    respond_to do |format|
      format.html { redirect_to presents_url }
      format.json { head :no_content }
    end
  end

  def taken_toggle
    @present = Present.find(params[:id])
    if @present.boolean == true
      @present.boolean = false
    else
      @present.boolean = true
    end
    @present.save
    redirect_to @present
  end



  private

  def present_params
    params.require(:present).permit(:name, :pole, :text, :boolean)

  end

  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/presents_helper.rb
module PresentsHelper

end

app/views/presents/_form.html.erb
<%= form_for(@present) do |f| %>
  <% if @present.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@present.errors.count, "error") %> prohibited this present from being saved:</h2>

      <ul>
      <% @present.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Název" %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label :text, "Text" %><br />
      <%= f.text_field :text %>
    </div>
  <div class="field">
   <%= f.label :pole, "Obsadit?" %><br />
    <%= f.check_box :pole, { }, "Obsazeno", "Volno" %>
  </div>  <br />
  <div class="actions">
    <%= f.submit "Potvrdit" %>
  </div>
<% end %>

app/views/presents/_present_form.html.erb
<% unless @present %>
    <div id="present_form">

          <%= render 'uvolnit' %>

          <%= render 'obsadit' %>

    </div>
<% end %>

app/views/presents/edit.html.erb
<div class="container marketing">
  <div class="row">
<h1>Změna daru</h1>


<%= form_for(@present) do |f| %>
    <% if @present.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@present.errors.count, "error") %> prohibited this present from being saved:</h2>

          <ul>
            <% @present.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h3>Dar:  <%= @present.name %></h3>




      <%= f.label :pole, "Obsadit?", :class => 'checkbox' do %>
      <%= f.check_box :pole, {}, "Obsazeno", "Volno" %>Obsaditi<% end %>


     <br />
    <div class="actions">
      <%= f.submit "Aktualizovat" %>
    </div>
<% end %>


<%= link_to 'Show', @present %> |
<%= link_to 'Back', presents_path %>
  </div>
    </div>

app/views/presents/index.html.erb
<div class="container marketing" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <div class="row">




    <h1>Seznam darů</h1>

<table class="table">
  <tr>
    <th>Název</th>
    <th>text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @presents.each do |present| %>
  <tr>
    <td><%= present.name %></td>
    <td><%= present.text %></td>
    <td class="polenahoru">
      <% if present.boolean %>
          Obsazeno
      <% else %>
          Volno
      <% end %></td>
      </td>
      <td><% if present.boolean %>
            <%= link_to "Obsazeno", taken_toggle_present_path(present), class: "btn btn-danger" %>
        <% else %>
            <%= link_to "Volno", taken_toggle_present_path(present), class: "btn btn-success" %>
        <% end %> </td>


    <td><%= link_to 'smazat', present, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>



<br>
    <br>
    <% if current_user && current_user.admin? %>
<%= link_to 'Nový dar', new_present_path %>


    <% end %>
 </div>
    </div>

app/views/presents/new.html.erb
<div class="container marketing">
  <div class="row">
<h1>Nový dar</h1>

<%= render 'form' %>

<%= link_to 'Zpět na seznam', presents_path %>

app/views/presents/show.html.erb
<div class="container marketing">
  <div class="row">
<p id="notice"><%= notice %></p>


<h3>Dar:  <%= @present.name %></h3>
<h4>Popis:<%= @present.text %></h4>

<p>
  <b>Stav:</b>
  <% if @present.boolean %>
  Obsazeno
   <% else %>
  Volno
      <% end %>

</p>


<%= link_to 'Změnit', edit_present_path(@present) %> |
<%= link_to 'Zpět', presents_path %>
  </div>
    </div>