config/routes.rb
Svatba::Application.routes.draw do

   root 'home#index'
   
    resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new' , via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'  , via: :get
  match '/dary',  to: 'presents#index'   , via: :get
  match '/snoubenci',  to: 'about_us#index'      , via: :get
  match '/snoubenci_galerie',  to: 'galleries#index'   , via: :get
  match '/zenich_galerie',  to: 'groom_galleries#index'  , via: :get
  match '/zenich',  to: 'groom#index'   , via: :get
  match '/nevesta',  to: 'bride#index'   , via: :get
  match '/nevesta_galerie',  to: 'bride#gallery'  , via: :get
  match '/home',    to: 'home#home'      , via: :get
  match '/aktuality',    to: 'home#aktuality'     , via: :get
  match '/dary',    to: 'home#dary'   , via: :get
  match '/program',    to: 'home#program'   , via: :get
  match '/kontakty',    to: 'home#kontakty'  , via: :get

  post "gallery/create"
  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :pictures

  resources :groom_galleries do
    resources :groom_pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :groom_pictures

  resources :bride_galleries do
    resources :bride_pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :bride_pictures

   resources :presents do
     member do
       get 'taken_toggle'
     end
end

  

end

app/models/groom_gallery.rb
class GroomGallery < ActiveRecord::Base
 has_many :groom_pictures, :dependent => :destroy
 attr_accessible :name, :description, :token, :cover

def generate_token
  self.token = loop do
    random_token = SecureRandom.urlsafe_base64
    break random_token unless GroomGallery.where(token: random_token).exists?
  end
end

end

app/controllers/groom_galleries_controller.rb
class GroomGalleriesController < ApplicationController
  def index
    @groom_galleries = GroomGallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groom_galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @groom_gallery = GroomGallery.find(params[:id])
    @groom_picture = @groom_gallery.groom_pictures.build
    @groom_pictures = GroomPicture.find(:all, :conditions  => [ 'groom_gallery_id = ?', @groom_gallery.id ])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @groom_gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @groom_gallery = GroomGallery.new
    @groom_gallery.token = @groom_gallery.generate_token
    @groom_picture = @groom_gallery.groom_pictures.build
    @groom_pictures = []

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @groom_gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @groom_gallery = GroomGallery.find(params[:id])
    @groom_picture = @groom_gallery.groom_pictures.build
    @groom_pictures = []
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @groom_gallery = GroomGallery.new(params.require(:groom_gallery).permit(:name, :description, :token, :cover))


    if @groom_gallery.save
      redirect_to groom_gallery_path(@groom_gallery), :notice => "Zipcode was saved sucessfully"
    else
      render new_groom_gallery_path
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @groom_gallery = GroomGallery.find(params[:id])

    respond_to do |format|
      if @groom_gallery.update_attributes(params[:groom_gallery_params])
        format.html { redirect_to @groom_gallery, notice: 'Galerie byla úspěšně aktualizováná.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @groom_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @groom_gallery = GroomGallery.find(params[:id])
    @groom_gallery.destroy

    respond_to do |format|
      format.html { redirect_to groom_galleries_url }
      format.json { head :no_content }
    end
  end

  private

  def groom_gallery_params
    params.require(:groom_gallery).permit(:description, :name)
  end

end

app/helpers/groom_galleries_helper.rb
module GroomGalleriesHelper
end

app/views/groom_galleries/_form.html.erb
<%= form_for @groom_gallery, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.hidden_field :token %>
    <div class="control-group">
      <%= f.label :name %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-mini btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  groom_galleries_path, :class => 'btn btn-mini' %>
    </div>
<% end %>




<%= javascript_include_tag 'jquery.ui.widget.js' %>
<%= javascript_include_tag 'jquery.iframe-transport.js' %>
<%= javascript_include_tag 'jquery.fileupload.js' %>
<%= javascript_include_tag 'jquery.fileupload-ui.js' %>

app/views/groom_galleries/edit.html.erb
<div class="container marketing">
  <div class="row">

    <%- model_class = @groom_gallery.class -%>
    <div class="page-header">
      <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                       :default => "Edit #{model_class.model_name.human}") %></h1>
    </div>
    <%= render :partial => 'form' %>
  </div></div>

app/views/groom_galleries/index.html.erb
<div class="container marketing">
  <div class="row">
    <%= render :template =>  'shared/zenich_nav' %>
    <h1>Gallerie ženicha</h1>
    <ul class="thumbnails files">
      <% @groom_galleries.each do |groom_gallery| %>
          <li class="span3" id="gallery_<%= groom_gallery.id %>">
            <div class="thumbnail">
              <% if groom_gallery.cover.blank? or !Gromm_picture.find_by_id(groom_gallery.cover) %>
                  <a href="<%= groom_gallery_path(:id => groom_gallery.id) %>">
                    <img src="/assets/NoImageAvailable.jpg" alt="">
                  </a>
              <% else %>
                  <a href="<%= groom_gallery_path(:id => groom_gallery.id) %>">
                    <img src="<%= Groom_picture.find_by_id(groom_gallery.cover).image.thumb.url %>" alt="">
                  </a>
              <% end %>
              <div class="caption">
                <p style="text-align: center;">
                 <!--  groom_gallery.name.truncate(14) -->
                  <a href="<%= edit_groom_gallery_path(:id => groom_gallery.id) %>" class="btn btn-mini">
                    <i class="icon-edit "></i>
                    Edit
                  </a>
                  <a class="btn btn-mini btn-delete" confirm="Вы уверены?" data-method="delete" href="<%= groom_gallery_path(:id => groom_gallery.id) %>" data-remote=true>
                    <i class="icon-trash"></i>
                    Delete
                  </a>
                </p>
              </div>
            </div>
          </li>
      <% end %>
    </ul>

    <%= link_to 'New', new_groom_gallery_path, :class => 'btn btn-mini' %>
  </div>  </div>

app/views/groom_galleries/new.html.erb
<div class="container marketing">
  <div class="row">

    <%- model_class = @groom_gallery.class -%>
    <div class="page-header">
      <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                       :default => "New #{model_class.model_name.human}") %></h1>
    </div>
    <%= render :partial => 'form' %>
  </div></div>

app/views/groom_galleries/show.html.erb
<div class="container marketing">

  <div class="row">
    <h1>Gallery</h1>

    <input type="hidden" id="galleryID" value="<%= @groom_gallery.id %>">

    <p>
      <b>Name: </b>
      <%= @groom_gallery.name %>
    </p>

    <p>
      <b>Description: </b>
      <%= @groom_gallery.description %>
    </p>

    <h2>Pictures</h2>
  </div>

  <%= form_for [@groom_gallery, @groom_picture], :html => { :multipart => true, :id => "fileupload"  } do |f| %>
      <div class="row">
        <div class=" fileupload-buttonbar">
          <div class="progressbar fileupload-progressbar nofade"><div style="width:0%;"></div></div>
      <span class="btn btn-mini fileinput-button">
        <i class="icon-plus"></i>
        <span><%= t('photos.add_files') %>...</span>
        <%= f.file_field :image %>
      </span>
        </div>
      </div>
      <br>
      <div class="row">
        <ul class="thumbnails files">
          <% unless @groom_pictures.empty? %>
              <% @groom_pictures.each do |pic| %>
                  <li class="span3" id="picture_<%= pic.id %>">
                    <div class="thumbnail">
                      <a href="<%= pic.image.url %>" rel="lightbox-pictures" title="<%= pic.description %>">
                        <img src="<%= pic.image.thumb.url %>" alt="">
                      </a>
                      <div class="caption">
                        <p style="text-align: center;">
                          <a href="/groom_galleries/<%= @groom_gallery.id %>/groom_pictures/<%= pic.id %>/edit" class="btn btn-mini">
                            <i class="icon-edit "></i>
                            Edit
                          </a>
                          <a class="btn btn-mini btn-delete" confirm="Вы уверены?" data-method="delete" href="/groom_galleries/<%= @groom_gallery.id %>/groom_pictures/<%= pic.id %>" data-remote=true>
                            <i class="icon-trash"></i>
                            Delete
                          </a>
                        </p>
                      </div>
                    </div>
                  </li>
              <% end %>
          <% end %>
        </ul>
      </div>
  <% end %>
  <script>
      var fileUploadErrors = {
          maxFileSize: 'File is too big',
          minFileSize: 'File is too small',
          acceptFileTypes: 'Filetype not allowed',
          maxNumberOfFiles: 'Max number of files exceeded',
          uploadedBytes: 'Uploaded bytes exceed file size',
          emptyResult: 'Empty file upload result'
      };
  </script>



  <script id="template-download" type="text/html">
    {% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
    <tr class="template-download nofade">
      {% if (file.error) { %}
      <td></td>
      <td class="name">{%=file.name%}</td>
      <td class="size">{%=o.formatFileSize(file.size)%}</td>
      <td class="error" colspan="2"><span class="label important">Error</span> {%=fileUploadErrors[file.error] || file.error%}</td>
      {% } else { %}
      <td class="preview">{% if (file.thumbnail_url) { %}
        <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery"><img src="{%=file.thumbnail_url%}"></a>
        {% } %}</td>
      <td class="name">
        <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}">{%=file.name%}</a>
      </td>
      <td class="size">{%=o.formatFileSize(file.size)%}</td>
      <td colspan="2"></td>
      {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"><%= t('photos.template.delete') %></button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
  </script>



  <%= javascript_include_tag 'jquery.ui.widget.js' %>
  <%= javascript_include_tag 'jquery.iframe-transport.js' %>
  <%= javascript_include_tag 'jquery.fileupload.js' %>
  <%= javascript_include_tag 'jquery.fileupload-ui.js' %>




  <div class="row">
    <div class="form-actions">
      <%= link_to 'Back', galleries_path, :class => 'btn btn-mini'  %>
      <%= link_to 'Edit', edit_gallery_path(@gallery), :class => 'btn btn-mini' %>
      <%= link_to 'Delete', gallery_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini' %>
    </div>
  </div>
</div>