config/routes.rb
Svatba::Application.routes.draw do

   root 'home#index'
   
    resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new' , via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'  , via: :get
  match '/dary',  to: 'presents#index'   , via: :get
  match '/snoubenci',  to: 'about_us#index'      , via: :get
  match '/snoubenci_galerie',  to: 'galleries#index'   , via: :get
  match '/zenich_galerie',  to: 'groom_galleries#index'  , via: :get
  match '/zenich',  to: 'groom#index'   , via: :get
  match '/nevesta',  to: 'bride#index'   , via: :get
  match '/nevesta_galerie',  to: 'bride#gallery'  , via: :get
  match '/home',    to: 'home#home'      , via: :get
  match '/aktuality',    to: 'home#aktuality'     , via: :get
  match '/dary',    to: 'home#dary'   , via: :get
  match '/program',    to: 'home#program'   , via: :get
  match '/kontakty',    to: 'home#kontakty'  , via: :get

  post "gallery/create"
  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :pictures

  resources :groom_galleries do
    resources :groom_pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :groom_pictures

  resources :bride_galleries do
    resources :bride_pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :bride_pictures

   resources :presents do
     member do
       get 'taken_toggle'
     end
end

  

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/about_nav.html.erb
<ul class="nav nav-pills nav-stacked"  style="width:200px; float: left">
  <li><%= link_to "Něco o nás", snoubenci_path %></li>
  <li><%= link_to "Naše galerie", snoubenci_galerie_path %></li>
</ul>

app/views/shared/nevesta_nav.html.erb
    <ul class="nav nav-pills nav-stacked"  style="width:200px; float: left">
      <li><%= link_to "Něco o mně", nevesta_path %></li>
      <li><%= link_to "Moje galerie", bride_galleries_path %></li>
    </ul>

app/views/shared/zenich_nav.html.erb
<ul class="nav nav-pills nav-stacked"  style="width:200px; float: left">
  <li><%= link_to "Něco o mně", zenich_path %></li>
  <li><%= link_to "Moje galerie", groom_galleries_path %></li>
</ul>