config/routes.rb
Svatba::Application.routes.draw do

   root 'home#index'
   
    resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new' , via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'  , via: :get
  match '/dary',  to: 'presents#index'   , via: :get
  match '/snoubenci',  to: 'about_us#index'      , via: :get
  match '/snoubenci_galerie',  to: 'galleries#index'   , via: :get
  match '/zenich_galerie',  to: 'groom_galleries#index'  , via: :get
  match '/zenich',  to: 'groom#index'   , via: :get
  match '/nevesta',  to: 'bride#index'   , via: :get
  match '/nevesta_galerie',  to: 'bride#gallery'  , via: :get
  match '/home',    to: 'home#home'      , via: :get
  match '/aktuality',    to: 'home#aktuality'     , via: :get
  match '/dary',    to: 'home#dary'   , via: :get
  match '/program',    to: 'home#program'   , via: :get
  match '/kontakty',    to: 'home#kontakty'  , via: :get

  post "gallery/create"
  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :pictures

  resources :groom_galleries do
    resources :groom_pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :groom_pictures

  resources :bride_galleries do
    resources :bride_pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :bride_pictures

   resources :presents do
     member do
       get 'taken_toggle'
     end
end

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def aktuality
  end

  def program
  end

  def kontakty
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/aktuality.html.erb
<div class="container marketing">

<div class="row">
<h1>Aktuality</h1>
  <p> Svatba je zatím v plánu</p>
</div>
</div>

app/views/home/home.html.erb
<div class="container marketing">

  <div class="row">
    <h1>Vítejte na stránkách Honzy a Radušky</h1>
    <p>
      Rádi bychom se Vám touto cestou představili a příblížili Vám, jak bude náš Velký den probíhat!
    </p>
  </div>
</div>

app/views/home/index.html.erb
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/bootstrap-transition.js"></script>
<script src="../assets/js/bootstrap-alert.js"></script>
<script src="../assets/js/bootstrap-modal.js"></script>
<script src="../assets/js/bootstrap-dropdown.js"></script>
<script src="../assets/js/bootstrap-scrollspy.js"></script>
<script src="../assets/js/bootstrap-tab.js"></script>
<script src="../assets/js/bootstrap-tooltip.js"></script>
<script src="../assets/js/bootstrap-popover.js"></script>
<script src="../assets/js/bootstrap-button.js"></script>
<script src="../assets/js/bootstrap-collapse.js"></script>
<script src="../assets/js/bootstrap-carousel.js"></script>
<script src="../assets/js/bootstrap-typeahead.js"></script>
<script>
    !function ($) {
        $(function(){
            // carousel demo
            $('#myCarousel').carousel()
        })
    }(window.jQuery)
</script>

<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag ("ruce.JPG") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Raduška a Honzík</h1>
          <p class="lead"></p>

          <%= link_to "Více o nás", snoubenci_path , class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag ("rada2.jpg") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Raduška Jasanská</h1>
          <p class="lead"></p>
          <%= link_to "Více o nevěstě", nevesta_path , class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </div>



    <div class="item">
      <%= image_tag ("honza2.JPG") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Honza Vykydal</h1>
          <p class="lead"></p>
          <%= link_to "Více o ženichovi", zenich_path, class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </div>
  </div>

  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>

</div><!-- /.carousel -->

<div class="zavrit">

  <%= link_to home_path do %>
      <%= image_tag("close.png") %> Zavřít<% end %>

</div>



  <!-- FOOTER -->
  <footer>

      </footer>

</div><!-- /.container -->



<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/bootstrap-transition.js"></script>
<script src="../assets/js/bootstrap-alert.js"></script>
<script src="../assets/js/bootstrap-modal.js"></script>
<script src="../assets/js/bootstrap-dropdown.js"></script>
<script src="../assets/js/bootstrap-scrollspy.js"></script>
<script src="../assets/js/bootstrap-tab.js"></script>
<script src="../assets/js/bootstrap-tooltip.js"></script>
<script src="../assets/js/bootstrap-popover.js"></script>
<script src="../assets/js/bootstrap-button.js"></script>
<script src="../assets/js/bootstrap-collapse.js"></script>
<script src="../assets/js/bootstrap-carousel.js"></script>
<script src="../assets/js/bootstrap-typeahead.js"></script>
<script>
    !function ($) {
        $(function(){
            // carousel demo
            $('#myCarousel').carousel()
        })
    }(window.jQuery)
</script>

app/views/home/kontakty.html.erb
<div class="container marketing">

  <div class="row">
    <h1>Kontakty</h1>
    <table  class="table"><tr class='success' ><td> Ženich - Jan Vykydal</td>   <td>(tel: 608700372, email: vykyjan(et)seznam.cz)  </td>  </tr>
    <tr class='success'><td>Nevěsta - Raduška Jasanská</td><td>(tel: 774345146, email: radulle(et)seznam.cz)</td>  </tr>
    <tr  class='success'><td> Svědek ženicha - Jakub Kočíř</td> </tr>
    <tr  class="success"> <td>Svědek nevěsty - Martinka Jasanská </td> </tr>
  </table>


  </div>
</div>

app/views/home/program.html.erb
<div class="container marketing">

  <div class="row">
    <h1>Program</h1>
    <p> Dobře se připravit na svatbu</p>
  </div>
</div>